import {
  mdiAccountLockOpen,
  mdiAccountLockOpenOutline,
  mdiAlignHorizontalDistribute,
  mdiAlignVerticalDistribute,
  mdiArrowBottomLeftBoldBox,
  mdiArrowBottomLeftBoldBoxOutline,
  mdiArrowBottomLeftThin,
  mdiArrowBottomRightBoldBox,
  mdiArrowBottomRightBoldBoxOutline,
  mdiArrowBottomRightThin,
  mdiArrowDownThin,
  mdiArrowLeftThin,
  mdiArrowRightThin,
  mdiArrowTopLeftBoldBox,
  mdiArrowTopLeftBoldBoxOutline,
  mdiArrowTopLeftThin,
  mdiArrowTopRightBoldBox,
  mdiArrowTopRightBoldBoxOutline,
  mdiArrowTopRightThin,
  mdiArrowUpThin,
  mdiBookmarkBoxMultiple,
  mdiBookmarkBoxMultipleOutline,
  mdiBullhornVariant,
  mdiBullhornVariantOutline,
  mdiCameraMarker,
  mdiCameraMarkerOutline,
} from "@mdi/js";

export const icons = [
  { mdi: mdiAccountLockOpen, name: "mdi-account-lock-open" },
  { mdi: mdiAccountLockOpenOutline, name: "mdi-account-lock-open-outline" },
  {
    mdi: mdiAlignHorizontalDistribute,
    name: "mdi-align-horizontal-distribute",
  },
  { mdi: mdiAlignVerticalDistribute, name: "mdi-align-vertical-distribute" },
  { mdi: mdiArrowBottomLeftBoldBox, name: "mdi-arrow-bottom-left-bold-box" },
  {
    mdi: mdiArrowBottomLeftBoldBoxOutline,
    name: "mdi-arrow-bottom-left-bold-box-outline",
  },
  { mdi: mdiArrowBottomLeftThin, name: "mdi-arrow-bottom-left-thin" },
  { mdi: mdiArrowBottomRightBoldBox, name: "mdi-arrow-bottom-right-bold-box" },
  {
    mdi: mdiArrowBottomRightBoldBoxOutline,
    name: "mdi-arrow-bottom-right-bold-box-outline",
  },
  { mdi: mdiArrowBottomRightThin, name: "mdi-arrow-bottom-right-thin" },
  { mdi: mdiArrowDownThin, name: "mdi-arrow-down-thin" },
  { mdi: mdiArrowLeftThin, name: "mdi-arrow-left-thin" },
  { mdi: mdiArrowRightThin, name: "mdi-arrow-right-thin" },
  { mdi: mdiArrowTopLeftBoldBox, name: "mdi-arrow-top-left-bold-box" },
  {
    mdi: mdiArrowTopLeftBoldBoxOutline,
    name: "mdi-arrow-top-left-bold-box-outline",
  },
  { mdi: mdiArrowTopLeftThin, name: "mdi-arrow-top-left-thin" },
  { mdi: mdiArrowTopRightBoldBox, name: "mdi-arrow-top-right-bold-box" },
  {
    mdi: mdiArrowTopRightBoldBoxOutline,
    name: "mdi-arrow-top-right-bold-box-outline",
  },
  { mdi: mdiArrowTopRightThin, name: "mdi-arrow-top-right-thin" },
  { mdi: mdiArrowUpThin, name: "mdi-arrow-up-thin" },
  { mdi: mdiBookmarkBoxMultiple, name: "mdi-bookmark-box-multiple" },
  {
    mdi: mdiBookmarkBoxMultipleOutline,
    name: "mdi-bookmark-box-multiple-outline",
  },
  { mdi: mdiBullhornVariant, name: "mdi-bullhorn-variant" },
  { mdi: mdiBullhornVariantOutline, name: "mdi-bullhorn-variant-outline" },
  { mdi: mdiCameraMarker, name: "mdi-camera-marker" },
  { mdi: mdiCameraMarkerOutline, name: "mdi-camera-marker-outline" },
];
